import type {
  EngineWorldContextCommand,
  EngineWorldObjectInput,
} from "./engine-contracts.js";

const policy = (
  kind: EngineWorldObjectInput["definition"]["criticalPolicy"]["kind"],
  options: Partial<Omit<EngineWorldObjectInput["definition"]["criticalPolicy"], "kind">> = {},
): EngineWorldObjectInput["definition"]["criticalPolicy"] => ({
  kind,
  canDestroy: true,
  canLose: true,
  canSell: true,
  canConsume: true,
  canHide: true,
  ...options,
});

const object = (
  id: string,
  sourceRef: string,
  name: string,
  description: string,
  material: EngineWorldObjectInput["definition"]["material"],
  tags: string[],
  affordances: EngineWorldObjectInput["definition"]["affordances"],
  state: EngineWorldObjectInput["state"],
  criticalPolicy: EngineWorldObjectInput["definition"]["criticalPolicy"],
  effectInteractions: EngineWorldObjectInput["definition"]["effectInteractions"] = [],
): EngineWorldObjectInput => ({
  id,
  definition: {
    key: id,
    sourceRef,
    name,
    description,
    material,
    tags,
    affordances,
    prerequisites: [],
    effectInteractions,
    weight: 1,
    criticalPolicy,
  },
  state,
  locationRef: "ruined-gatehouse",
});

export const RUINED_GATEHOUSE_OBJECTS: readonly EngineWorldObjectInput[] = [
  object(
    "gatehouse-door",
    "fixture:ruined-gatehouse:wooden-door",
    "Wooden gatehouse door",
    "A swollen wooden door secured by an iron lock.",
    "wood",
    ["door", "breakable"],
    ["inspect", "open", "close", "lock", "unlock", "break", "damage"],
    "locked",
    policy("alternate_path", { canLose: false, canSell: false, canConsume: false, recoveryRef: "gatehouse-bridge" }),
  ),
  object(
    "gatehouse-crate",
    "fixture:ruined-gatehouse:movable-crate",
    "Movable supply crate",
    "A rough crate that can be shifted across the threshold.",
    "wood",
    ["crate", "container", "movable", "breakable"],
    ["inspect", "move", "carry", "throw", "take", "drop", "break", "damage"],
    "intact",
    policy("ordinary_consequence"),
  ),
  object(
    "gatehouse-weapon",
    "fixture:ruined-gatehouse:metal-weapon",
    "Dropped metal weapon",
    "A serviceable metal weapon abandoned beside the wall.",
    "metal",
    ["weapon", "metal"],
    ["inspect", "take", "carry", "throw", "drop", "steal", "equip", "use", "damage"],
    "intact",
    policy("ordinary_consequence"),
  ),
  object(
    "gatehouse-rope",
    "fixture:ruined-gatehouse:rope",
    "Waxed rope",
    "A coil of rope with enough length to attach to a fixed point.",
    "rope",
    ["rope", "tether"],
    ["inspect", "take", "carry", "throw", "drop", "attach", "use"],
    "intact",
    policy("ordinary_consequence"),
  ),
  object(
    "gatehouse-oil",
    "fixture:ruined-gatehouse:oil-container",
    "Oil container",
    "A sealed container of lamp oil.",
    "oil",
    ["container", "flammable"],
    ["inspect", "take", "carry", "drop", "use", "ignite", "extinguish"],
    "wet",
    policy("ordinary_consequence"),
  ),
  object(
    "gatehouse-fire",
    "fixture:ruined-gatehouse:fire-source",
    "Fire source",
    "A brazier still carrying a steady flame.",
    "fire",
    ["fire-source"],
    ["inspect", "ignite", "extinguish", "activate"],
    "lit",
    policy("ordinary_consequence", { canConsume: false }),
  ),
  object(
    "gatehouse-lever",
    "fixture:ruined-gatehouse:breakable-lever",
    "Breakable gate lever",
    "A rusted lever connected to the gate mechanism.",
    "metal",
    ["lever", "breakable", "switch"],
    ["inspect", "activate", "attach", "break", "damage"],
    "inactive",
    policy("world_transformation", { canLose: false, canSell: false, canConsume: false }),
    [{ affordance: "activate", targetId: "gatehouse-door", targetState: "open" }],
  ),
  object(
    "gatehouse-clue",
    "fixture:ruined-gatehouse:important-clue",
    "Important gatehouse clue",
    "A waxed clue strip naming the safe route around the collapsed bridge.",
    "paper",
    ["clue", "critical"],
    ["inspect", "take", "carry", "drop", "use", "break", "damage"],
    "intact",
    policy("recoverable_route", { canDestroy: false, recoveryRef: "gatehouse-inscription" }),
  ),
];

export function ruinedGatehouseWorldContextCommand(): EngineWorldContextCommand {
  return {
    kind: "world_context",
    title: "Ruined gatehouse",
    description: "A collapsed gatehouse frames a locked door, a broken bridge mechanism, and the last safe route clue.",
    features: ["collapsed bridge", "gatehouse-threshold"],
    exits: [],
    objects: {
      upsert: RUINED_GATEHOUSE_OBJECTS.map((entry) => ({
        ...entry,
        definition: {
          ...entry.definition,
          tags: [...entry.definition.tags],
          affordances: [...entry.definition.affordances],
          prerequisites: entry.definition.prerequisites.map((prerequisite) => ({ ...prerequisite, requiredTags: [...prerequisite.requiredTags] })),
          effectInteractions: entry.definition.effectInteractions.map((interaction) => ({ ...interaction })),
          criticalPolicy: { ...entry.definition.criticalPolicy },
        },
      })),
    },
  };
}
